Repository The-Major-Project/Design-and-Develop-frontend, pull requests merged in 2021-09, with the labels that each got.

#4 Updated package.json
  package-lock.json
  package.json
  yarn.lock
Labels: Story

#7 added custom fonts
  src/fonts/gilroy/Gilroy-Black.ttf
  src/fonts/gilroy/Gilroy-BlackItalic.ttf
  src/fonts/gilroy/Gilroy-Bold.ttf
  src/fonts/gilroy/Gilroy-BoldItalic.ttf
  src/fonts/gilroy/Gilroy-ExtraBold.ttf
  src/fonts/gilroy/Gilroy-ExtraBoldItalic.ttf
  src/fonts/gilroy/Gilroy-Heavy.ttf
  src/fonts/gilroy/Gilroy-HeavyItalic.ttf
  src/fonts/gilroy/Gilroy-Light.ttf
  src/fonts/gilroy/Gilroy-LightItalic.ttf
  src/fonts/gilroy/Gilroy-Medium.ttf
  src/fonts/gilroy/Gilroy-MediumItalic.ttf
  src/fonts/gilroy/Gilroy-Regular.ttf
  src/fonts/gilroy/Gilroy-RegularItalic.ttf
  src/fonts/gilroy/Gilroy-SemiBold.ttf
  src/fonts/gilroy/Gilroy-SemiBoldItalic.ttf
  src/fonts/gilroy/Gilroy-Thin.ttf
  src/fonts/gilroy/Gilroy-ThinItalic.ttf
  src/fonts/gilroy/Gilroy-UltraLight.ttf
  src/fonts/gilroy/Gilroy-UltraLightItalic.ttf
  src/index.css
  src/index.js
Labels: enhancement

#10 mv-input-component
  src/components/shared/Input/index.js
Labels: Story

#9 Added button component with loading state
  package.json
  src/components/Button/index.js
  src/components/Loader/index.js
  tailwind.config.js
  yarn.lock
Labels: Story

#17 Ys footer
  src/components/Footer/index.js
Labels: Story

#18 Mv header auth
  src/components/Header/index.js
  src/components/Input/index.js
Labels: Story

#19 Staging
  src/components/Footer/index.js
  src/components/Header/index.js
  src/components/Input/index.js
Labels: enhancement

#20 Mv input component
  src/components/Input/index.js
Labels: bug

#21 signup module and header fixes
  src/assets/shared/authsvg.svg
  src/assets/shared/underline2.svg
  src/components/Header/index.js
  src/modules/auth/signup/index.js
Labels: bug, Story

#23 Add license 1
  LICENSE
Labels: documentation

#25 Staging
  LICENSE
  src/assets/shared/authsvg.svg
  src/assets/shared/underline2.svg
  src/components/Header/index.js
  src/components/Input/index.js
  src/modules/auth/signup/index.js
Labels: bug, Story

#27 Ys login
  src/modules/auth/login/index.js
Labels: Story

#28 1-Landing page 2-Framer animations 3- Header fixes 4-Routing
  src/Routes/Routes.js
  src/assets/About.png
  src/assets/Contact.png
  src/assets/Hero.png
  src/assets/Navigate.png
  src/assets/faq1.svg
  src/assets/faq2.svg
  src/assets/faq3.svg
  src/components/Header/index.js
  src/index.css
  src/modules/Home.js
  src/modules/landingPage/_components/faq's/faq.data.js
  src/modules/landingPage/_components/faq's/index.js
  src/modules/landingPage/_components/whyMoveEasy/index.js
  src/modules/landingPage/_components/whyMoveEasy/why.data.js
  src/modules/landingPage/index.js
Labels: bug, enhancement, Story

#31 Print data to console
  src/App.css
  src/App.js
  src/Routes/Routes.js
  src/index.css
  src/modules/auth/login/index.js
Labels: bug

#30 Fixed scrollbar
  src/App.css
  src/App.js
  src/index.css
Labels: bug

#33 Fixed bugs of landingpage
  src/modules/landingPage/_components/whyMoveEasy/index.js
  src/modules/landingPage/index.js
Labels: bug

#41 Ys context
  src/App.js
  src/context/DNDContext.js
Labels: Story

#45 Ys login integrated
  package.json
  src/api/api.js
  src/modules/auth/login/index.js
  yarn.lock
Labels: Story

#46 Auth integration
  package.json
  src/api/api.js
  src/components/Button/index.js
  src/modules/auth/login/index.js
  src/modules/auth/signup/index.js
Labels: enhancement

#52 added tostify to signup
  src/modules/auth/signup/index.js
Labels: enhancement, Story

#53 Mv toster bugs
  src/modules/auth/login/index.js
  src/modules/auth/signup/index.js
Labels: bug

#54 Staging
  src/modules/auth/login/index.js
  src/modules/auth/signup/index.js
Labels: bug

#61 Mv token generation
  src/Routes/Routes.js
  src/modules/auth/login/index.js
  src/modules/dashboard/index.js
Labels: Story

#68 Mv dashboard layout
  src/Routes/Routes.js
  src/assets/Ham.svg
  src/components/Layout/index.js
  tailwind.config.js
Labels: bug, Story

#72 Integrated emailjs in contact form.
  package-lock.json
  package.json
  src/modules/landingPage/index.js
Labels: Story

#71 Added hero banner comp
  src/assets/HandShake.png
  src/components/DashboradBanner/index.js
Labels: Story

#77 Mv small bugs
  src/assets/DashboardIcons/Logout.svg
Labels: bug

#79 fixed header bugs
  src/components/Layout/index.js
Labels: bug

#83 implemented profile sider for notifications
  src/assets/avatar.jpg
  src/assets/avatar2.jpg
  src/components/NotificationSider/index.js
Labels: Story

#82 Mj dashboard ppost card
  src/assets/DashboardIcons/icon.png
  src/components/DashboardPostCard/index.js
  src/modules/dashboard/index.js
Labels: Story
